### ISSUE TITLE
2019: Open Areas of Investigation

### ISSUE THREAD

**Issue by mikeday** [yeslogic/ddl#150]
## TODO

- [x] revisiting evaluation/normalisation? ([brendanzab/rust-nbe-for-mltt](https://github.com/brendanzab/rust-nbe-for-mltt))
- [x] revisiting naming/binding? (pikelet-lang/pikelet#181)
- [x] property testing of type system and generated parsers (using [AltSysrq/proptest](https://github.com/AltSysrq/proptest) perhaps?)
- [x] metavariable solving, for implicit arguments (eg. as in [AndrasKovacs/smalltt](https://github.com/AndrasKovacs/smalltt), but doesn't need to be super quick)
- [ ] Dependent pattern matching (#148)
- [x] Host/Repr type issues (#101, #120)
